// Code generated by gen_catalog.mjs from openai/codex models-manager/models.json
// (Apache-2.0, https://github.com/openai/codex/blob/main/codex-rs/models-manager/models.json).
// DO NOT EDIT BY HAND. Regenerate: node gen_catalog.mjs < models.json > catalog.go

package codex

type modelCatalogEntry struct {
	DisplayName             string
	Description             string
	ContextWindow           int64
	MaxContextWindow        int64
	WebSearchToolType       string
	SupportsSearchTool      bool
	InputModalities         []string
	ToolMode                string
	SupportsParallelCalls   bool
	ReasoningLevels         []string
	ExperimentalTools       []string
	AvailableInPlans        []string
}

var modelCatalog = map[string]modelCatalogEntry{
	"gpt-5.6-sol": {
		DisplayName:           "GPT-5.6-Sol",
		Description:           "Latest frontier agentic coding model.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "code_mode_only",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh","max","ultra"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.6-terra": {
		DisplayName:           "GPT-5.6-Terra",
		Description:           "Balanced agentic coding model for everyday work.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "code_mode_only",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh","max","ultra"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.6-luna": {
		DisplayName:           "GPT-5.6-Luna",
		Description:           "Fast and affordable agentic coding model.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "code_mode_only",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh","max"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.5": {
		DisplayName:           "GPT-5.5",
		Description:           "Frontier model for complex coding, research, and real-world work.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.4": {
		DisplayName:           "GPT-5.4",
		Description:           "Strong model for everyday coding.",
		ContextWindow:         272000,
		MaxContextWindow:      1000000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","go","hc","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.4-mini": {
		DisplayName:           "GPT-5.4-Mini",
		Description:           "Small, fast, and cost-efficient model for simpler coding tasks.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"gpt-5.2": {
		DisplayName:           "GPT-5.2",
		Description:           "Optimized for professional work and long-running agents.",
		ContextWindow:         272000,
		MaxContextWindow:      272000,
		WebSearchToolType:     "text",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","free","free_workspace","go","hc","k12","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
	"codex-auto-review": {
		DisplayName:           "Codex Auto Review",
		Description:           "Automatic approval review model for Codex.",
		ContextWindow:         272000,
		MaxContextWindow:      1000000,
		WebSearchToolType:     "text_and_image",
		SupportsSearchTool:    true,
		InputModalities:       []string{"text","image"},
		ToolMode:              "",
		SupportsParallelCalls: true,
		ReasoningLevels:       []string{"low","medium","high","xhigh"},
		ExperimentalTools:     []string{},
		AvailableInPlans:      []string{"business","edu","edu_plus","edu_pro","education","enterprise","enterprise_cbp_automation","enterprise_cbp_usage_based","finserv","go","hc","plus","pro","prolite","quorum","sci","self_serve_business_usage_based","team"},
	},
}
