#!/usr/bin/env node
// Generates catalog.go from the official openai/codex models-manager snapshot.
//
//   node gen_catalog.mjs < models.json > catalog.go
//
// Source: https://raw.githubusercontent.com/openai/codex/main/codex-rs/models-manager/models.json
// (openai/codex, Apache-2.0). Regenerate whenever a new model family ships.
// Only the fields the gateway surfaces are extracted; instructions templates
// and other client-only payloads are intentionally dropped.

import { readFileSync } from 'node:fs';

const raw = readFileSync(0, 'utf8');
const { models } = JSON.parse(raw);

const esc = (value) => JSON.stringify(value ?? '');

const goSlice = (items) => `[]string{${items.map((item) => JSON.stringify(item)).join(',')}}`;

const lines = [
  '// Code generated by gen_catalog.mjs from openai/codex models-manager/models.json',
  '// (Apache-2.0, https://github.com/openai/codex/blob/main/codex-rs/models-manager/models.json).',
  '// DO NOT EDIT BY HAND. Regenerate: node gen_catalog.mjs < models.json > catalog.go',
  '',
  'package codex',
  '',
  'type modelCatalogEntry struct {',
  '\tDisplayName             string',
  '\tDescription             string',
  '\tContextWindow           int64',
  '\tMaxContextWindow        int64',
  '\tWebSearchToolType       string',
  '\tSupportsSearchTool      bool',
  '\tInputModalities         []string',
  '\tToolMode                string',
  '\tSupportsParallelCalls   bool',
  '\tReasoningLevels         []string',
  '\tExperimentalTools       []string',
  '\tAvailableInPlans        []string',
  '}',
  '',
  'var modelCatalog = map[string]modelCatalogEntry{',
];

for (const model of models) {
  const slug = model.slug;
  const reasoning = (model.supported_reasoning_levels ?? []).map((level) => level.effort);
  lines.push(`\t${JSON.stringify(slug)}: {`);
  lines.push(`\t\tDisplayName:           ${esc(model.display_name)},`);
  lines.push(`\t\tDescription:           ${esc(model.description)},`);
  lines.push(`\t\tContextWindow:         ${Number(model.context_window) || 0},`);
  lines.push(`\t\tMaxContextWindow:      ${Number(model.max_context_window) || 0},`);
  lines.push(`\t\tWebSearchToolType:     ${esc(model.web_search_tool_type)},`);
  lines.push(`\t\tSupportsSearchTool:    ${Boolean(model.supports_search_tool)},`);
  const modalities = goSlice(model.input_modalities ?? []);
  lines.push(`\t\tInputModalities:       ${modalities},`);
  lines.push(`\t\tToolMode:              ${esc(model.tool_mode)},`);
  lines.push(`\t\tSupportsParallelCalls: ${Boolean(model.supports_parallel_tool_calls)},`);
  lines.push(`\t\tReasoningLevels:       ${goSlice(reasoning)},`);
  lines.push(`\t\tExperimentalTools:     ${goSlice(model.experimental_supported_tools ?? [])},`);
  lines.push(`\t\tAvailableInPlans:      ${goSlice(model.available_in_plans ?? [])},`);
  lines.push('\t},');
}

lines.push('}');
process.stdout.write(`${lines.join('\n')}\n`);
